### ISSUE TITLE
Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by SpainTrain** [AtomLinter/linter-markdown#10]
Possibly related to updaing mdast in #9 

**Atom Version**: 1.2.4
**System**: Ubuntu 15.10
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package, v1.2.2

### Stack Trace

Uncaught TypeError: callback is not a function

```
At /home/spainhower/.atom/packages/linter-markdown/node_modules/mdast/lib/cli/configuration.js:288

TypeError: callback is not a function
    at handleLocalConfiguration (/home/spainhower/.atom/packages/linter-markdown/node_modules/mdast/lib/cli/configuration.js:288:9)
    at /home/spainhower/.atom/packages/linter-markdown/node_modules/mdast/lib/cli/configuration.js:207:9
    at /home/spainhower/.atom/packages/linter-markdown/node_modules/mdast/node_modules/vfile-find-up/index.js:207:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "linter-jshint"
    ],
    "ignoredName": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".thing*"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".thing*"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sass-Syntax-Highlight, v0.1.1
ScssBundle, v0.5.0
atom-jade, v0.3.0
auto-detect-indentation, v0.4.2
autocomplete-emojis, v2.2.2
autocomplete-modules, v1.3.0
autocomplete-python, v1.2.2
bug-report, v0.7.1
editor-stats, v0.17.0
exception-reporting, v0.37.0
go-plus, v3.5.2
language-SCSS, v0.4.0
language-docker, v1.1.6
language-javascript-better, v1.7.1
language-markdown, v0.5.1
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-eslint, v5.2.6
linter-js-yaml, v1.2.5
linter-jscs, v3.2.0
linter-jsonlint, v1.1.0
linter-less, v2.3.1
linter-markdown, v1.2.2
linter-pep8, v1.0.1
linter-pylama, v0.2.2
linter-pylint, v1.2.0
linter-scss-lint, v2.4.0
metrics, v0.53.1
react, v0.12.10
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
linter-pylint, v1.2.0
```

**Comment by SpainTrain** [comment]
Also getting

```
TypeError: Cannot read property 'plugins' of undefined

TypeError: Cannot read property 'plugins' of undefined
    at _Class.module.exports._Class.lint (/home/spainhower/.atom/packages/linter-markdown/lib/linter.coffee:64:41)
    at _Class.lint (/home/spainhower/.atom/packages/linter-markdown/lib/linter.coffee:1:1)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/spainhower/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/spainhower/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/spainhower/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/spainhower/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /home/spainhower/.atom/packages/linter/lib/editor-linter.js:80:22
    at /home/spainhower/.atom/packages/linter/lib/helpers.coffee:23:18
````

**Comment by Arcanemagus** [comment]
We really need basic CI testing on all the repos, even if it's just to catch stuff like this...

**Comment by SpainTrain** [comment]
Yup, perhaps some evening I'll see about making a little yeoman generator (or similar) for that.  Extra points for creating a script that opens PRs on CI-less repos.

**Comment by wooorm** [comment]
Darn, didn’t know this package already reads `.mdastrc` files which, indeed, changed. Working on this.
