### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval'

### ISSUE THREAD

**Issue by ndelangen** [AtomLinter/linter-markdown#138]
I'm getting this error:
```log
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'". at Function.line.toFunction (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/generate-function/index.js:55:21) at compile (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:558:23) at visit (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:333:16) at /Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:536:9 at Array.forEach (native) at visit (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:533:31) at compile (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:552:3) at module.exports (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:581:10) at Object.<anonymous> (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/eslint/lib/testers/rule-tester.js:76:24) at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1) at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1) at Module.load (module.js:473:32) at tryModuleLoad (module.js:432:12) at Function.Module._load (module.js:424:3) at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45) at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1) at Object.<anonymous> (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/eslint/lib/api.js:11:17) at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1) at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1) at Module.load (module.js:473:32) at tryModuleLoad (module.js:432:12) at Function.Module._load (module.js:424:3) at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45) at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1) at Object.<anonymous> (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/remark-lint-code-eslint/index.js:1:93) at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1) at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1) at Module.load (module.js:473:32) at tryModuleLoad (module.js:432:12) at Function.Module._load (module.js:424:3) at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45) at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1) at modOrString (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/remark-lint-code/index.js:22:36) at Function.Linter.from (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/remark-lint-code/index.js:42:13) at /Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/remark-lint-code/index.js:11:28 at Array.forEach (native) at lintCode (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/remark-lint-code/index.js:9:24) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:74:16 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:57:9) at /Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:82:42 at wrap (/Users/dev/.atom/packages/linter-markdown/node_modules/wrapped/index.js:54:27) at transformer (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-lint-rule/index.js:34:7) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at Object.run (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:48:10) at executor (/Users/dev/.atom/packages/linter-markdown/node_modules/unified/index.js:299:20) at Function.run (/Users/dev/.atom/packages/linter-markdown/node_modules/unified/index.js:296:5) at transform (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-engine/lib/file-pipeline/transform.js:18:21) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:128:19) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at then (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:174:5) at wrapped (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:149:9) at next (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:81:24) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/trough/index.js:163:12) at handleConfiguration (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-engine/lib/file-pipeline/configure.js:68:5) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:76:14) at apply (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:176:7) at applyAll (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:166:7) at found (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:158:7) at done (/Users/dev/.atom/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:149:9) at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) (remark-lint:code)
```

This is my config:
```json
{
  "plugins": [
    "remark-preset-lint-recommended",
    ["remark-lint-list-item-indent", false],
    ["remark-lint-code", {"js": {
      "module": "node_modules/remark-lint-code-eslint",
      "options": {
        "fix": true
      }
    }}],
    ["remark-toc", {
      "tight": true,
      "maxDepth": 3
    }]
  ]
}
```
<img width="1771" alt="screen shot 2017-05-27 at 20 10 03" src="https://cloud.githubusercontent.com/assets/3070389/26523472/a4e13eb0-4318-11e7-974d-86e51f84b1bf.png">

**Comment by ndelangen** [comment]
When I run `remark .` in the terminal everything works as expected.

**Comment by wooorm** [comment]
Probably something related to Atom!

Could you try an remove each plugin to check out which one is causing this? Hint: I’m guessing it’s ESLint related.

**Comment by ndelangen** [comment]
I have disabled all addons excluding: 

<img width="760" alt="screen shot 2017-05-27 at 22 36 23" src="https://cloud.githubusercontent.com/assets/3070389/26524241/f9209c5a-432c-11e7-8076-bb5855395e52.png">

Yet I still have the message:
```log
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'". at Function.line.toFunction (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/generate-function/index.js:55:21) at compile (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:558:23) at visit (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:333:16) at /Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:536:9 at Array.forEach (native) at visit (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:533:31) at compile (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:552:3) at module.exports (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/is-my-json-valid/index.js:581:10) at Object.<anonymous> (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/eslint/lib/testers/rule-tester.js:76:24) at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1) at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1) at Module.load (module.js:473:32) at tryModuleLoad (module.js:432:12) at Function.Module._load (module.js:424:3) at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45) at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1) at Object.<anonymous> (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/eslint/lib/api.js:11:17) at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1) at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1) at Module.load (module.js:473:32) at tryModuleLoad (module.js:432:12) at Function.Module._load (module.js:424:3) at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45) at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1) at Object.<anonymous> (/Users/dev/Projects/GitHub/storybook/react-storybook/node_modules/remark-lint-code-eslint/index.js:1:93) at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1) at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1) at Module.load (module.js:473:32) at tryModuleLoad (module.js:432:12) at Function.Module._load (module.js:424:3) (remark-lint:code
```

the markdown is:
```md
# Website for [storybook.js.org](https://storybook.js.org)

This is the source for [storybook.js.org](https://storybook.js.org). It documents [Storybook](https://github.com/storybooks/storybook), an amazing UI component development environment for React and React Native. The site is built with [Gatsby](https://github.com/gatsbyjs/gatsby).

### Usage

```sh
npm i
npm run develop
npm run storybook
```

### Edit Documentation

Documentation is written in Markdown and located inside the [`pages/`](pages/) directory.

```

**Comment by ndelangen** [comment]
whoops wrong button

**Comment by wooorm** [comment]
Okay, so it is remark related?!
Sorry, I wasn’t very clear, 😧 I meant to ask if you could try and remove each remark plugin in your `.remarkrc`, could you try that too?

**Comment by wooorm** [comment]
@ndelangen Friendly ping!

**Comment by ndelangen** [comment]
It's definitely related to the:
```
["remark-lint-code", {"js": {
  "module": "node_modules/remark-lint-code-eslint",
  "options": {
    "fix": true
  }
}}],
```

If I remove that, error is gone.

I've given up and disabled the atom-plugin. Would care a lot if this were to function correctly!

**Comment by wooorm** [comment]
Thanks for checking this out, Norbert!

This seems to be related to things that ESLint does. The [`remark-lint-code-eslint`](https://github.com/Qard/remark-lint-code-eslint/blob/master/index.js) plugin essentially calls ESLint’s `engine.executeOnText`.

So, maybe it doesn’t like some config options in your eslintrc file? Or it doesn’t deal with `fix: true`?
I don’t know, this feels like ESLint’s territory, and it explodes in Atom, and I have no idea why!

**Comment by ndelangen** [comment]
I think it's related to the way eslint is executed, but I have no suggestion on how to fix, but that's from what I've read about the issue.

When running in the terminal everything is fine, and eslint actually does auto-fix code inside markdown.

**Comment by wooorm** [comment]
> I think it's related to the way eslint is executed, but I have no suggestion on how to fix, but that's from what I've read about the issue.

Atom has different rules compared to Node, for security reasons. @Arcanemagus, do you have ideas on this?

> When running in the terminal everything is fine, and eslint actually does auto-fix code inside markdown.

Really? It autofixes? You may be right, but I don’t [see any code here](https://github.com/Qard/remark-lint-code-eslint/blob/1e1dcc2b37221be8e0b3091ed4a3e9758a1deead/index.js#L7) to suggest that? How are you running things?

**Comment by Arcanemagus** [comment]
> Atom has different rules compared to Node, for security reasons. @Arcanemagus, do you have ideas on this?

This is... tricky. It looks like this is being caused by a sub-sub-dependency of ESLint generating functions on the fly for some reason. It _might_ be possible to work around this using [loophole](https://github.com/atom/loophole), but that only works for some cases. The other alternative is to move execution of `remark` to a worker process (that doesn't have the same security restrictions that package code in Atom has), but that's a rather large undertaking.

> Really? It autofixes?

@wooorm It's passed the `options` [here](https://github.com/Qard/remark-lint-code-eslint/blob/1e1dcc2b37221be8e0b3091ed4a3e9758a1deead/index.js#L4) which would enable autofixing. Note however @ndelangen that that will likely only work on the command line, if it works in Atom it is likely updating the file on disk which may or may not horribly mess up your editor contents in Atom 😛.

**Comment by wooorm** [comment]
>  It's passed the options here which would enable autofixing.

The options are given, yes, but `node.value` isn’t changed. So if this is working, `engine.executeOnText(node.value, file.path)` actually modifies `file.path`, which I find incredibly weird too.

**Comment by wooorm** [comment]
This is not something we can fix here. It’s a problem in eslint or remark-lint-code-eslint.
