### ISSUE TITLE
Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../../../../.....

### ISSUE THREAD

**Issue by aleksnavarro** [AtomLinter/linter-markdown#254]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: KDE neon
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.10

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../../../../../home/aleks/Proyectos/CUCEI/6Semestre/I5903/Expo01/filososcomensales.md"

```
At /home/aleks/.atom-profiles/Atom-Markdown/packages/linter-markdown/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../../../../../../../../home/aleks/Proyectos/CUCEI/6Semestre/I5903/Expo01/filososcomensales.md"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
```

### Commands

```
     -0:40.6.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:23 tree-view:add-file (span.name.icon.icon-file-directory)
  8x -0:20.3.0 core:backspace (input.hidden-input)
     -0:13.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autosave-onchange 1.5.1 
busy-signal 2.0.1 
custom-title 1.0.1 
intentions 1.1.5 
language-markdown 0.37.0 
linter 2.3.1 
linter-markdown 5.2.10 
linter-ui-default 1.8.0 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.16.3 
markdown-writer 2.11.9 
tool-bar 1.1.12 
tool-bar-markdown-writer 0.5.0 
```

**Comment by kiil** [comment]
I get the same error on MacOS

**Comment by rugk** [comment]
Getting the same error. Atom is installed as a flatpak here. Fedora 30

----

[Enter steps to reproduce:]

1. Edit a markdown file.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: linux 5.2.18-200.fc30.x86_64
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../../../../home/rugk/Software/own/add-on/how-did-i-get-here/CONTRIBUTING.md"

```
At /var/home/rugk/.var/app/io.atom.Atom/data/packages/linter-markdown/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../../../../../../../home/rugk/Software/own/add-on/how-did-i-get-here/CONTRIBUTING.md"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)
```

### Commands

```
  2x -1:22.2.0 markdown-preview:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:58.2.0 intentions:highlight (input.hidden-input)
     -0:57 core:select-down (input.hidden-input)
     -0:56.3.0 intentions:highlight (input.hidden-input)
     -0:56.2.0 core:paste (input.hidden-input)
     -0:49.8.0 editor:newline (input.hidden-input)
     -0:47.5.0 intentions:highlight (input.hidden-input)
     -0:47.3.0 settings-view:open (input.hidden-input)
     -0:03.0 intentions:highlight (input.hidden-input)
     -0:02.7.0 core:save (input.hidden-input)
```

**Comment by ferdnyc** [comment]
Only data point I can add is, I just got this immediately on launch (no actions taken at all), when loading a _non_-markdown file. Though it might heuristically have appeared to be Markdown. (`backtrace.gdb` contains the output of a `bt` command in `gdb`, meaning 50-something lines that begin with `#n `, where `n` is an integer that starts at `0` and increments on each subsequent line.)

<details>

<summary>Crash details from the Atom error popup

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: "Fedora release
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.10
</summary>

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../gsconnect/backtrace.gdb"

```
At /home/ferd/.atom/packages/linter-markdown/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../gsconnect/backtrace.gdb"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-updater-linux 1.3.0 
autocomplete-asciidoc 0.1.2 
autocomplete-java-minus 0.14.0 
autocomplete-modules 2.3.0 
autocomplete-python 1.16.0 
blame 1.2.0 
box-edit 0.1.3 
build-cmake 0.12.0 
busy 0.7.0 
busy-signal 2.0.1 
color-picker 2.3.0 
conventional-changelog 0.1.0 
editorconfig 2.5.0 
gcc-make-run 0.2.12 
gitlab 0.1.3-7 
hey-pane 1.2.0 
ide-css 0.3.3 
ide-java 0.9.0 
ide-json 0.2.1 
ide-python 1.5.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
java-classpath-registry 0.4.0 
java-import-wiz 0.5.0 
language-asciidoc 1.11.0 
language-cmake 1.2.0 
language-cuda 0.1.0 
language-diff 0.7.0 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-inform7 1.0.2 
language-javascript-plus 3.0.0 
language-mediawiki 2.2.0 
language-meson 0.2.1 
language-ninja 1.1.0 
language-qt-qrc 3.0.0 
language-qtpro 0.7.0 
language-restructuredtext 1.1.2 
language-rpm-spec 0.16.0 
language-svg 0.9.2 
language-swig-wrapper 0.2.0 
linter 2.3.1 
linter-alex 7.0.0 
linter-gcc2 0.8.7 
linter-js-yaml 1.4.6 
linter-jsonlint 1.4.0 
linter-markdown 5.2.10 
linter-pycodestyle 2.1.3 
linter-travis-lint 1.0.2 
linter-ui-default 1.8.0 
open-all 0.3.0 
project-manager 3.3.8 
regex-railroad-diagram 0.19.4 
rst-preview 1.3.1 
rst-preview-pandoc 0.1.12 
sort-lines 0.19.0 
svg-preview 0.14.0 
tabs-to-spaces 1.0.5 
todo-show 2.3.2 
trailing-spaces 0.4.0 
zentabs 0.8.9 
```

**Comment by pdxwolfy** [comment]
I'm seeing this issue on macOS 10.15.2 with Atom 1.42.0 and Linter-Markdown 5.2.11. This leaves linter-markdown completely unusable.

**Comment by pdxwolfy** [comment]
I uninstalled all of my packages, then reinstalled. That seems to have fixed the issue with linter-markdown.

**Comment by AlexWayfer** [comment]
My own:

Steps to reproduce:

1. Open Atom on [AlexWayfer/flame-flash](https://github.com/AlexWayfer/flame-flash) repository.
2. That's all.

**Atom**: 1.46.0 x64
**Electron**: 4.2.12
**OS**: "Arch Linux"
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.11


### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../flame-flash/README.md"

```
At /home/alex/.atom/packages/linter-markdown/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../flame-flash/README.md"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-smart-tabs 0.1.0 
atom-typescript 13.6.0 
auto-detect-indentation 1.3.0 
auto-update-plus 0.5.8 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autocomplete-ruby 0.2.8 
autocomplete-ruby-rct 0.1.0 
autoupdate-packages 1.3.1 
ax-monokai-syntax 0.3.0 
better-git-blame 0.5.0 
blocky 0.13.0 
busy-signal 2.0.1 
change-line-length 0.1.1 
color-picker 2.3.0 
editorconfig 2.6.0 
file-icons 2.1.41 
file-watcher 2.0.0 
genesis-ui 0.5.0 
git-time-machine 2.1.0 
go-plus 6.1.0 
goto-definition 1.3.4 
highlight-selected 0.17.0 
hyperclick 0.1.5 
ide-crystal 0.3.3 
ide-ruby 0.5.0 
ide-yaml 0.7.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-crystal-actual 0.37.2 
language-fish-shell 1.1.0 
language-haml 0.32.1 
language-markdown 0.37.0 
language-postcss 1.3.1 
language-typescript-react 0.1.1 
language-vue 0.26.0 
linter 2.3.1 
linter-erb 1.1.5 
linter-eslint 8.5.5 
linter-htmlhint 1.6.3 
linter-jshint 3.1.19 
linter-markdown 5.2.11 
linter-reek 2.4.2 
linter-rubocop 2.5.7 
linter-ruby 1.3.1 
linter-slim 2.0.0 
linter-spell 0.15.0 
linter-spell-ruby 0.4.0 
linter-stylelint 4.5.1 
linter-ui-default 1.8.1 
linter-ui-plus 0.3.2 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
monocolor-blue-syntax 2.0.0 
monokai 0.24.0 
monokai-flat 1.0.1 
monokai-plus 0.1.3 
monokai-pro 0.1.0 
monokai-slate 0.6.0 
monokai-sublime 1.0.0 
nord-atom-syntax 0.10.0 
northem-atom-syntax 2.1.0 
northem-dark-atom-syntax 2.1.0 
nucleus-dark-ui 0.12.3 
one-monokai 0.3.0 
platformio-ide-terminal 2.10.0 
precss 0.3.0 
remember-file-positions 0.2.3 
revert-buffer 0.6.0 
robe 0.4.3 
ruby-block 0.3.6 
ruby-block-converter 4.1.1 
ruby-define-method 0.2.2 
ruby-navigator 0.5.0 
ruby-slim 0.2.0 
ruby-test 1.0.2 
scroll-editor-on-middle-click 0.7.0 
seeing-is-believing 15.0.0 
seti-icons 1.5.4 
seti-ui 1.11.0 
single-click-open 0.2.2 
slim-language 2.2.0 
space-tab 0.4.2 
space-underscore 0.1.1 
split-diff 1.6.1 
stacked-tabs 0.1.3 
symbols-tree-view 0.14.0 
sync-settings 4.3.3 
tab-control 0.6.11 
tabs-to-spaces 1.0.5 
tasks 2.10.1 
teletype 0.13.4 
term3 0.22.1 
toggle-quotes 1.1.4 
tree-view-open-files 0.3.0 
yaml-path 0.1.1 
yard 0.5.1 
zentabs 0.8.9 
```

**Comment by AlexWayfer** [comment]
@Arcanemagus @wooorm can we somehow fix it please? There are too many duplicates of this issue, and it's a pretty annoying, to be honest.

**Comment by wooorm** [comment]
@AlexWayfer I don’t think anyone maintains this project anymore. I’ve used linter-remark since 2016.

**Comment by AlexWayfer** [comment]
> @AlexWayfer I don’t think anyone maintains this project anymore. I’ve used linter-remark since 2016.

OK, thank you. It's sad. The whole Atom and its ecosystem seems dying. :pensive:

**Comment by wooorm** [comment]
Personally, I still happily use Atom, just not this plugin!

**Comment by DanBuchan** [comment]
To be honest I've just done 2 fresh installs of Atom and I'm not seeing this error. As best I can tell is install order for some packages messes this up (or not)!

Not entirely helpful but is in line with  pdxwolfy's suggestion

**Comment by AlexWayfer** [comment]
Work-around: add `package.json`, my content of it:

```json
{
	"scripts": {
		"remark": "remark -f ."
	},
	"devDependencies": {
		"remark-cli": "^9.0.0",
		"remark-gfm": "^1.0.0",
		"remark-preset-lint-recommended": "^5.0.0"
	}
}
```

**Comment by DerZyklop** [comment]
I have this exact error with another linter: [linthtml](https://github.com/linthtml/linthtml). 
Could be related.

**Comment by DerZyklop** [comment]
I have this exact same error with another linter: [linthtml](https://github.com/linthtml/linthtml).
Could be related.

I fixed it by changing my command
`linthtml './src/**/*.html'`
to
`linthtml 'src/**/*.html'`
Hope this helps you guys.
✌

**Comment by s-light** [comment]
this error just appeared for me today...
would be good to exclude the user-file-string from the auto-lookup-and-reporting for errors.. as this leads to the duplicates...

**Comment by dhmmasson** [comment]
**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.13.6
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.11

Same errors only happened when I opened the project folder from the command line 
``` bash
atom .
```

I then proceed to close the project, and open it from the menu and the error disappeared.
