### ISSUE TITLE
Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../../../../Sy...

### ISSUE THREAD

**Issue by BenLeggiero** [AtomLinter/linter-markdown#257]
Gonna guess this involves Catalina's "magic" of keeping the system in one volume and the user in another.

1. Open a Markdown file
2. 💥

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15.1
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.10

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../../../../System/Volumes/Data/Users/benleggiero/Google Drive/Libraries/Projects/From Me/Swift-Style-Guidelines/_includes/guidelines/punctuation.md"

```
At /Users/benleggiero/.atom/packages/linter-markdown/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../../../../../../../System/Volumes/Data/Users/benleggiero/Google Drive/Libraries/Projects/From Me/Swift-Style-Guidelines/_includes/guidelines/punctuation.md"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
highlight-selected 0.16.0 
intentions 1.1.5 
language-liquid 0.7.0 
linter 2.3.1 
linter-markdown 5.2.10 
linter-sass-lint 1.9.0 
linter-scss-lint 3.2.1 
linter-ui-default 1.8.0 
linter-ui-plus 0.3.2 
linter-yaml 1.1.0 
markdown-toolbar 0.1.2 
markdown-writer 2.11.9 
material-colors 0.1.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
minimap-selection 4.5.0 
one-dark-material-syntax 1.0.3 
remote-ftp 2.2.2 
scss-snippets 0.6.0 
Sublime-Style-Column-Selection 1.7.5 
tool-bar 1.2.0 
tool-bar-atom 1.7.0 
tool-bar-markdown 0.8.0 
tool-bar-markdown-writer 0.5.0 
```

**Comment by AlexWayfer** [comment]
I guess it's duplicate of #254.

**Comment by AlexWayfer** [comment]
If you upvoted the comment about duplication — can you please transfer your logs into the original one and close this?
