### ISSUE TITLE
Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../../../../va...

### ISSUE THREAD

**Issue by kotewa** [AtomLinter/linter-markdown#258]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.10

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../../../../var/projects/environments/xxx-yyy/aws/infrastructure-docs/README.md"

```
At /Users/krzysztof.kotewa/.atom/packages/linter-markdown/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../../../../../../../var/projects/environments/xxx-yyy/aws/infrastructure-docs/README.md"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

### Commands

```
```

### Non-Core Packages

```
ansible-galaxy 0.2.1 
ansible-vault 0.7.8 
atom-jinja2 0.6.0 
autocomplete-ansible 0.1.24 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
click-link 1.0.11 
docker 0.8.0 
file-icons 2.1.36 
git-history 3.3.0 
git-log 0.4.1 
git-plus 8.7.1 
git-time-machine 2.1.0 
highlight-selected 0.16.0 
intentions 1.1.5 
language-ansible 0.2.2 
language-apache 1.8.0 
language-docker 1.1.8 
language-ini 1.23.0 
language-jenkinsfile 0.1.1 
language-markdown 0.37.0 
language-plantuml 0.2.0 
language-rpm-spec 0.16.0 
linter 2.3.1 
linter-ansible-syntax 1.2.3 
linter-docker 0.3.2 
linter-jenkins 1.0.6 
linter-markdown 5.2.10 
linter-shellcheck 1.6.0 
linter-ui-default 1.8.0 
markdown-table-editor 1.1.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
plantuml-viewer 0.7.2 
platformio-ide-terminal 2.10.0 
pretty-json 2.1.2 
project-manager 3.3.8 
python-tools 0.6.9 
remote-sync 4.1.8 
simple-drag-drop-text 0.5.0 
sort-lines 0.19.0 
split-diff 1.6.1 
todo-show 2.3.2 
tool-bar 1.2.0 
tree-view-git-status 1.5.2 
zentabs 0.8.9 
```

**Comment by AlexWayfer** [comment]
I guess it's duplicate of #257 and #254.
