### ISSUE TITLE
Uncaught RangeError: path should be a `path.relative()`d string, but got "../baselinemodels.jl/do...

### ISSUE THREAD

**Issue by oxinabox** [AtomLinter/linter-markdown#282]
Not sure what is causing,
I open some markdown files and I get spammed with this. 

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.11

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../baselinemodels.jl/docs/src/examples.md"

```
At /Users/oxinabox/.atom/packages/linter-markdown/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../baselinemodels.jl/docs/src/examples.md"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

### Commands

```
```

### Non-Core Packages

```
all-shades-of-blue-syntax 0.5.5 
atom-beautify 0.33.4 
autocomplete-haskell 1.0.1 
busy-signal 2.0.1 
colorblind-wombat-dark-syntax 0.6.0 
hex-view 0.2.1 
indent-detective 0.4.0 
ink 0.12.0 
intentions 1.1.5 
julia-client 0.12.0 
language-fish-shell 1.1.0 
language-haskell 1.19.4 
language-haskell-scoped 0.1.1 
language-julia 0.19.2 
language-markdown 0.37.0 
latex-completions 0.3.6 
linter 2.3.1 
linter-markdown 5.2.11 
linter-ui-default 1.8.1 
markdown-preview-plus 3.11.5 
newbound-dark-syntax 1.1.0 
pubster-syntax 3.1.0 
TabNine 2.1.7 
todo 0.6.0 
tool-bar 1.2.0 
uber-juno 0.3.0 
```

**Comment by AlexWayfer** [comment]
I think it's duplicate of #258, #257 and #254.
