### ISSUE TITLE
Uncaught RangeError: path should be a `path.relative()`d string, but got "../..\..\..\Users\icach...

### ISSUE THREAD

**Issue by icacho-dev** [AtomLinter/linter-markdown#300]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package 5.2.11

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "..\..\..\..\Users\icacho\Desktop\QA-API\SP-4414\README.md"

```
At C:\Users\icacho\.atom\packages\linter-markdown\node_modules\ignore\index.js:366

RangeError: path should be a `path.relative()`d string, but got "..\..\..\..\Users\icacho\Desktop\QA-API\SP-4414\README.md"
    at throwError (/packages/linter-markdown/node_modules/ignore/index.js:366:9)
    at checkPath (/packages/linter-markdown/node_modules/ignore/index.js:385:12)
    at Ignore._test (/packages/linter-markdown/node_modules/ignore/index.js:502:5)
    at Ignore.ignores (/packages/linter-markdown/node_modules/ignore/index.js:541:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
```

### Commands

```
     -0:58 intentions:highlight (input.hidden-input)
     -0:57.8.0 tree-view:toggle (input.hidden-input)
undefined -0:56.3.0 intentions:highlight (input.hidden-input)
     -0:00.3.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-cfn-lint 0.7.0 
atom-typescript 14.2.1 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
colorful-json 1.1.0 
dracula-syntax 3.0.2 
dracula-ui 0.6.0 
duplicate-removal 0.1.3 
file-icons 2.1.47 
highlight-selected 0.17.0 
ide-json 0.2.1 
ide-typescript 0.9.1 
intentions 1.1.5 
json-converter 0.2.4 
language-csv 1.1.2 
language-fish-shell 1.1.0 
language-groovy 0.7.0 
language-jenkinsfile 0.1.1 
language-log 1.10.1 
linter 3.3.1 
linter-eslint 8.6.5 
linter-js-yaml 1.4.6 
linter-jsonlint 1.4.0 
linter-markdown 5.2.11 
linter-ui-default 3.3.1 
minimap 4.39.10 
minimap-find-and-replace 5.0.8 
minimap-highlight-selected 4.6.5 
minimap-split-diff 0.3.7 
pretty-json 2.1.2 
rainbow-csv 1.4.0 
sort-lines 0.19.0 
split-diff 1.6.1 
styri-syntax 1.0.0 
tablr 1.8.3 
tidy-markdown 3.0.1 
```

**Comment by AlexWayfer** [comment]
I think it's a duplicate of #296, #294, #293, #290, #282, #258, #257, #254.
