### ISSUE TITLE
Uncaught SyntaxError: Cannot read configuration file: /Users/mglaman/Projects/ng-github/package.j...

### ISSUE THREAD

**Issue by mglaman** [AtomLinter/linter-markdown#39]
Have an empty package.json. Extension is buggering out over the fact

1. ...
2. ...

**Atom Version**: 1.5.1
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package, v1.4.2

### Stack Trace

Uncaught SyntaxError: Cannot read configuration file: /Users/mglaman/Projects/ng-github/package.json
Unexpected end of input

```
At /Users/mglaman/.atom/packages/linter-markdown/node_modules/remark/lib/cli/configuration.js:139

SyntaxError: Cannot read configuration file: /Users/mglaman/Projects/ng-github/package.json
Unexpected end of input
    at Object.parse (native)
    at load (/Users/mglaman/.atom/packages/linter-markdown/node_modules/remark/lib/cli/configuration.js:134:34)
    at /Users/mglaman/.atom/packages/linter-markdown/node_modules/remark/lib/cli/configuration.js:189:21
    at /Users/mglaman/.atom/packages/linter-markdown/node_modules/remark/node_modules/vfile-find-up/index.js:207:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:24.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:23.8.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
 10x -0:21.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:16.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:15.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:14.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:14.1.0 core:select-left (atom-text-editor.editor.is-focused)
  3x -0:11.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.0 core:save (atom-text-editor.editor.is-focused)
  6x -0:05.4.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:03.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:00.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.3.2
atom-material-ui, v0.8.1
bottom-dock, v0.3.7
build-grunt, v0.4.0
grunt-manager, v0.1.15
grunt-runner, v0.11.0
jshint, v1.8.3
language-docker, v1.1.6
linter, v1.11.3
linter-csslint, v1.2.0
linter-docker, v0.1.2
linter-markdown, v1.4.2
linter-php, v1.1.8
linter-scss-lint, v2.5.1
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by wooorm** [comment]
...And Could it be that the package.json file in ng-github is broken?

**Comment by mglaman** [comment]
@wooorm well, the package.json file was empty. I wouldn't assume an empty file would trigger warning notifications of a bug in my editor.

**Comment by mglaman** [comment]
Also I just realized the editor launched me into the linter-markdown extension, which makes no sense. I'll just close this, because fluke.
