### ISSUE TITLE
Failed to load the linter-markdown package

### ISSUE THREAD

**Issue by auser** [AtomLinter/linter-markdown#66]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package, v1.5.2

### Stack Trace

Failed to load the linter-markdown package

```
At Cannot find module 'remark/lib/cli/configuration.js'

Error: Cannot find module 'remark/lib/cli/configuration.js'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/auser/.atom/packages/linter-markdown/lib/index.js:10:23)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs",
      "nuclide",
      "pretty-json",
      "custom-title",
      "language-terraform",
      "language-swig",
      "language-nunjucks",
      "minimap",
      "fuse",
      "motepair",
      "atom-pair",
      "language-swig-wrapper",
      "emmet",
      "language-lisp",
      "formatter-json",
      "pigments",
      "relative-numbers",
      "language-javascript-jsx",
      "atom-typescript",
      "fonts",
      "language-lua",
      "dockerletion",
      "build-dockerfile",
      "linter-jshint"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-fusion-syntax, v1.1.0
atom-ternjs, v0.14.1
atomatigit, v1.5.5
autocomplete-go, v1.1.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.3
autoupdate-packages, v1.3.1
builder-go, v1.0.0
docblockr, v0.7.3
easy-motion-redux, v1.1.0
environment, v1.2.0
file-icons, vundefined
git-plus, vundefined
go-config, v1.1.4
go-debug, v0.1.12
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-line, v0.11.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
language-diff, v0.4.0
linter, v1.11.4
linter-eslint, v7.2.2
linter-flake8, v1.13.0
linter-markdown, v1.5.2
markdown-scroll-sync, v2.1.2
merge-conflicts, v1.4.3
navigator-godef, v1.0.3
nucleus-dark-ui, v0.8.0
project-plus, v0.9.0
proton-mode, v0.10.1
python-isort, v0.0.7
python-tools, v0.6.7
python-yapf, v0.10.0
react, v0.15.0
react-snippets, v0.4.2
recent-files-fuzzy-finder, v0.2.4
release-notes, v0.53.0
tester-go, v1.0.4
vim-mode-plus, v0.42.0
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by wooorm** [comment]
@auser That’s a weird error, which shouldn’t occur. I’m thinking it’s a problem with npm not correctly installing a dependency. Could you uninstall and re-install linter-markdown?

**Comment by auser** [comment]
Ah, didn't see your response... that didn't help :/

**Comment by Arcanemagus** [comment]
If you open the folder manually does the file show up?

If you go into the folder in a CLI and type `apm install` and restart Atom does it then work?

**Comment by wooorm** [comment]
@auser Any luck?

**Comment by wooorm** [comment]
As it’s been a while, I’m closing this. Please open a new issue if there’s still a problem.

**Comment by plaindocs** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package, v2.0.1


### Stack Trace

Failed to load the linter-markdown package

```
At /home/samuel/.atom/packages/linter-markdown/node_modules/unified-engine-atom/index.js:72
    return new Promise((resolve, reject) => {
                                       ^
missing ) after argument list

/home/samuel/.atom/packages/linter-markdown/node_modules/unified-engine-atom/index.js:72
    return new Promise((resolve, reject) => {
                                       ^
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/samuel/.atom/packages/linter-markdown/lib/index.js:11:16)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
linter-markdown, v2.0.1
linter-proselint, v3.0.1
pretty-json, v1.6.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@plaindocs Your version of Atom is from almost a year ago, which is positively ancient at the pace Atom develops at 😛. Update to the latest version and it should work for you.
