### ISSUE TITLE
Uncaught SyntaxError: Cannot read configuration file: /Users/nonameolsson/Development/smpw/packag...

### ISSUE THREAD

**Issue by nonameolsson** [AtomLinter/linter-markdown#68]
[Enter steps to reproduce below:]

1. Opened my README.md file.
2. I get the error on save file.

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-markdown](https://github.com/AtomLinter/linter-markdown) package, v1.5.2

### Stack Trace

Uncaught SyntaxError: Cannot read configuration file: /Users/nonameolsson/Development/smpw/package.json
Unexpected token <

```
At /Users/nonameolsson/.atom/packages/linter-markdown/node_modules/remark/lib/cli/configuration.js:145

SyntaxError: Cannot read configuration file: /Users/nonameolsson/Development/smpw/package.json
Unexpected token <
  at Object.parse (native)
  at load (/Users/nonameolsson/.atom/packages/linter-markdown/node_modules/remark/lib/cli/configuration.js:139:38)
  at /Users/nonameolsson/.atom/packages/linter-markdown/node_modules/remark/lib/cli/configuration.js:211:21
  at /Users/nonameolsson/.atom/packages/linter-markdown/node_modules/remark/node_modules/vfile-find-up/index.js:207:17
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -7:52.6.0 core:delete (atom-text-editor.editor.is-focused)
     -7:28.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -7:26.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:17 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:16.8.0 core:save (atom-text-editor.editor.is-focused)
     -7:02.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -6:35 core:close (div.panels-item)
     -6:32.3.0 core:save (atom-text-editor.editor.is-focused)
     -6:31.2.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-genesis-syntax.theme-one-dark-ui)
     -0:24.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:12.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:00.6.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "autocomplete-php",
      "dash-on-cursor",
      "autohide-tree-view",
      "nuclide-tabs",
      "atom-react-native-autocomplete",
      "atom-react-native-css",
      "meteor-api",
      "language-gfm",
      "php-debug",
      "linter-stylelint",
      "symbol-gen",
      "atom-ctags",
      "autocomplete-ctags",
      "linter-tidy",
      "atom-csscomb",
      "gulp-manager",
      "project-viewer",
      "linter",
      "tree-view",
      "tree-view-autoresize",
      "linter-flow",
      "tree-view-breadcrumb",
      "source-preview-babel",
      "ide-flow",
      "atom-typescript",
      "atom-autocomplete-php",
      "linter-php",
      "symbols-tree-view",
      "language-babel",
      "file-hyperclick"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-ternjs"
    ],
    "projectHome": "/Users/nonameolsson/Development/",
    "themes": [
      "one-dark-ui",
      "genesis-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.29.7
atom-jade, v0.3.0
atom-ternjs, v0.14.1
atom-yeoman, v0.3.15
auto-update-packages, v1.0.1
autocomplete-html-entities, v0.1.0
autocomplete-json, v1.11.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-wordpress-hooks, v0.2.0
bottom-dock, v0.4.4
build, v0.64.0
build-gulp, v0.9.0
build-npm-apm, v0.12.0
busy, v0.5.0
clipboard-plus, v0.5.1
color-picker, v2.1.1
editorconfig, v1.4.1
emmet, v2.4.3
file-icons, v1.7.12
genesis-syntax, v1.0.7
git-log, v0.4.1
haskell-grammar, v0.4.0
highlight-line, v0.11.1
highlight-selected, v0.11.2
html2haml, v0.10.0
hyperclick, v0.0.36
jQuery, v1.2.4
jade-beautify, v0.1.4
js-hyperclick, v1.4.2
json-colorer, v0.3.0
language-haml, v0.24.0
language-ini, v1.16.0
language-javascript-jsx, v0.3.7
language-markdown, v0.13.0
language-ocaml, v1.1.2
language-pug, v0.0.17
language-thrift, v1.0.2
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-haml, v1.2.0
linter-jade, v0.3.2
linter-jsonlint, v1.2.5
linter-jsxhint, v0.1.2
linter-markdown, v1.5.2
linter-pug-lint, v0.2.0
linter-scss-lint, v3.0.4
linter-ui-default, v0.0.3
merge-conflicts, v1.4.3
minimap, v4.24.3
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
multi-cursor, v2.1.3
npm-helper, v0.8.5
nuclide, v0.139.0
pigments, v0.27.1
pretty-json, v1.4.0
project-manager, v2.9.7
react, v0.15.0
react-snippets, v0.4.2
recent-files-fuzzy-finder, v0.2.4
simple-drag-drop-text, v0.3.1
source-preview-pug, v0.2.0
source-preview-react, v0.2.0
swackets, v0.10.0
terminal-plus, v0.14.5
tool-bar, v0.4.0
tree-view-git-branch, v0.1.2
tree-view-git-modified, v0.6.2
tree-view-open-files, v0.3.0
you-complete-me, v0.7.7

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like you have some invalid code in your `package.json` (A stray `<` where there shouldn't be.

**Comment by wooorm** [comment]
@nonameolsson This is an issue with your `package.json`, not with this linter.
